"use strict";
exports.__esModule = true;
var Square_1 = require("./Figure/Square");
var Circle_1 = require("./Figure/Circle");
var Rectangle_1 = require("./Figure/Rectangle");
var Triangle_1 = require("./Figure/Triangle");
var square = new Square_1.Square('Square', 'blue', 5);
square.printFormula();
console.log(square.calculateArea());
var circle = new Circle_1.Circle('Circle', 'turquoise', 6);
console.log(circle.calculateArea());
var rec = new Rectangle_1.Rectangle('Rectangle', 'green', 5, 8);
rec.printFormula();
console.log(rec.calculateArea());
var triangle = new Triangle_1.Triangle('Triangle', 'red', 3, 4, 5);
console.log(triangle.calculateArea());
